#include "resources/resources.hpp"
#include "../glad/glad.h"
#include <GLFW/glfw3.h>
#include <cstddef>
#include <iostream>
#include "VAO/VAO.hpp"
#include "VBO/VBO.hpp"
#include "EBO/EBO.hpp"
#include <math.h>
#include <vector>
#include "Shaders/ShadersClass.hpp"
#include "objects/objects.hpp"
#include "Textures//Textures.hpp"
#include <initializer_list>